services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./backend/logs:/app/logs
    environment:
      - PORT=3000
      - FIRESTORE_DATABASE_ID=vocab-database

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - BACKEND_URL=http://backend:3000
